// <auto-generated />
using System;
using DailyNagger.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailyNagger.Server.Data.Migrations.Data
{
    [DbContext(typeof(DailyNaggerDbContext))]
    [Migration("20260724111940_AddNaggerPinnedBy")]
    partial class AddNaggerPinnedBy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DailyNagger.Server.Domain.Nagger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ActiveLogDueOn")
                        .HasColumnType("date")
                        .HasColumnName("active_log_due_on");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("expires_on");

                    b.Property<bool>("IsDeactivated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deactivated");

                    b.Property<string>("PinnedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("None")
                        .HasColumnName("pinned_by");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedByClientId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("updated_by_client_id");

                    b.Property<string>("UpdatedByDeviceModel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("updated_by_device_model");

                    b.Property<string>("UpdatedByDeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("updated_by_device_name");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("IsDeactivated", "ActiveLogDueOn")
                        .HasDatabaseName("IX_nag_is_deactivated_active_log_due_on");

                    b.ToTable("nag");
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.ScheduleRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("Day")
                        .HasColumnType("int")
                        .HasColumnName("day");

                    b.Property<int?>("Month")
                        .HasColumnType("int")
                        .HasColumnName("month");

                    b.Property<Guid>("NagId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("nag_id");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("rule_type");

                    b.Property<int?>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("NagId");

                    b.ToTable("schedule_rule", (string)null);
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.TaskEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("InteractionAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("interaction_at");

                    b.Property<string>("InteractionLocale")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("interaction_locale");

                    b.Property<string>("InteractionMood")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("interaction_mood");

                    b.Property<DateTimeOffset?>("InteractionMoodAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("interaction_mood_at");

                    b.Property<string>("InteractionTimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("interaction_time_zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("label");

                    b.Property<string>("LastTaskRunReferenceValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("last_task_run_reference_value");

                    b.Property<Guid>("ParentTaskItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_task_item_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("Tag")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tag");

                    b.Property<Guid>("TaskLogId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("task_log_id");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("value_type");

                    b.HasKey("Id");

                    b.HasIndex("ParentTaskItemId");

                    b.HasIndex("TaskLogId");

                    b.ToTable("task_entry", (string)null);
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("DescendantTaskItemCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("descendant_task_item_count");

                    b.Property<int>("DoneDescendantTaskItemCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("done_descendant_task_item_count");

                    b.Property<DateTimeOffset?>("InteractionAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("interaction_at");

                    b.Property<string>("InteractionLocale")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("interaction_locale");

                    b.Property<string>("InteractionMood")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("interaction_mood");

                    b.Property<DateTimeOffset?>("InteractionMoodAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("interaction_mood_at");

                    b.Property<string>("InteractionTimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("interaction_time_zone");

                    b.Property<bool>("IsDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_done");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentTaskItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_task_item_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("Tag")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tag");

                    b.Property<Guid>("TaskLogId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("task_log_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentTaskItemId");

                    b.HasIndex("TaskLogId");

                    b.ToTable("task_item", (string)null);
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.TaskLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("closed_on");

                    b.Property<Guid?>("CopiedFromTaskLogId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("copied_from_task_log_id");

                    b.Property<int>("DescendantTaskItemCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("descendant_task_item_count");

                    b.Property<int>("DoneDescendantTaskItemCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("done_descendant_task_item_count");

                    b.Property<Guid>("NagId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("nag_id");

                    b.Property<string>("Tag")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tag");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedByClientId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("updated_by_client_id");

                    b.Property<string>("UpdatedByDeviceModel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("updated_by_device_model");

                    b.Property<string>("UpdatedByDeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("updated_by_device_name");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CopiedFromTaskLogId");

                    b.HasIndex("NagId");

                    b.HasIndex("NagId", "ClosedOn", "UpdatedAt")
                        .HasDatabaseName("IX_task_log_nag_id_closed_on_updated_at");

                    b.ToTable("task_log", null, t =>
                        {
                            t.HasCheckConstraint("ck_task_log_updated_at_not_default", "updated_at > '0001-01-01T00:00:00+00:00'");
                        });
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.UserMood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByClientId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("created_by_client_id");

                    b.Property<string>("CreatedByDeviceModel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("created_by_device_model");

                    b.Property<string>("CreatedByDeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("created_by_device_name");

                    b.Property<string>("Locale")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("locale");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mood");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("recorded_at");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("time_zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RecordedAt")
                        .HasDatabaseName("IX_user_mood_user_id_recorded_at");

                    b.ToTable("user_mood", (string)null);
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.UserTag", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("TagType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tag_type");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name")
                        .UseCollation("Latin1_General_100_CS_AS");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_used_at");

                    b.HasKey("UserId", "TagType", "Name");

                    b.ToTable("user_tag", (string)null);
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.ScheduleRule", b =>
                {
                    b.HasOne("DailyNagger.Server.Domain.Nagger", null)
                        .WithMany("ScheduleRules")
                        .HasForeignKey("NagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.TaskEntry", b =>
                {
                    b.HasOne("DailyNagger.Server.Domain.TaskItem", null)
                        .WithMany("TaskEntries")
                        .HasForeignKey("ParentTaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DailyNagger.Server.Domain.TaskLog", null)
                        .WithMany()
                        .HasForeignKey("TaskLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.TaskItem", b =>
                {
                    b.HasOne("DailyNagger.Server.Domain.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("ParentTaskItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DailyNagger.Server.Domain.TaskLog", null)
                        .WithMany("TaskItems")
                        .HasForeignKey("TaskLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.TaskLog", b =>
                {
                    b.HasOne("DailyNagger.Server.Domain.Nagger", null)
                        .WithMany()
                        .HasForeignKey("NagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.Nagger", b =>
                {
                    b.Navigation("ScheduleRules");
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.TaskItem", b =>
                {
                    b.Navigation("TaskEntries");
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.TaskLog", b =>
                {
                    b.Navigation("TaskItems");
                });
#pragma warning restore 612, 618
        }
    }
}
