// <auto-generated />
using System;
using DailyNagger.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailyNagger.Server.Data.Migrations.Data
{
    [DbContext(typeof(DailyNaggerDbContext))]
    [Migration("20260605193815_InitialDataSchema")]
    partial class InitialDataSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DailyNagger.Server.Domain.Nag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ActiveLogDueOn")
                        .HasColumnType("date")
                        .HasColumnName("active_log_due_on");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("expires_on");

                    b.Property<bool>("IsDeactivated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deactivated");

                    b.Property<DateTimeOffset>("ScheduleUpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("schedule_updated_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("IsDeactivated", "ActiveLogDueOn")
                        .HasDatabaseName("IX_nag_is_deactivated_active_log_due_on");

                    b.ToTable("nag", (string)null);
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.NagInput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("label");

                    b.Property<Guid>("NagLogId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("nag_log_id");

                    b.Property<Guid>("ParentNagNodeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_nag_node_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unit");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("value");

                    b.Property<string>("PreviousValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("previous_value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("value_type");

                    b.HasKey("Id");

                    b.HasIndex("NagLogId");

                    b.HasIndex("ParentNagNodeId");

                    b.ToTable("nag_input", (string)null);
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.NagInputUnitSuggestion", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unit");

                    b.HasKey("UserId", "Unit");

                    b.ToTable("nag_input_unit_suggestion", (string)null);
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.NagLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("closed_on");

                    b.Property<Guid?>("CopiedFromNagLogId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("copied_from_nag_log_id");

                    b.Property<Guid>("NagId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("nag_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("version")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CopiedFromNagLogId");

                    b.HasIndex("NagId");

                    b.HasIndex("NagId", "ClosedOn", "UpdatedAt")
                        .HasDatabaseName("IX_nag_log_nag_id_closed_on_updated_at");

                    b.ToTable("nag_log", t =>
                        {
                            t.HasCheckConstraint(
                                "ck_nag_log_updated_at_not_default",
                                "updated_at > '0001-01-01T00:00:00+00:00'");
                        });
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.NagNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("NagLogId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("nag_log_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentNagNodeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_nag_node_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("NagLogId");

                    b.HasIndex("ParentNagNodeId");

                    b.ToTable("nag_node", (string)null);
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.NagTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("int")
                        .HasColumnName("day_of_month");

                    b.Property<string>("DayOfWeek")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("day_of_week");

                    b.Property<int?>("MonthOfYear")
                        .HasColumnType("int")
                        .HasColumnName("month_of_year");

                    b.Property<Guid>("NagId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("nag_id");

                    b.Property<string>("TimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("time_type");

                    b.HasKey("Id");

                    b.HasIndex("NagId");

                    b.ToTable("nag_time", (string)null);
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.NagInput", b =>
                {
                    b.HasOne("DailyNagger.Server.Domain.NagLog", null)
                        .WithMany()
                        .HasForeignKey("NagLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DailyNagger.Server.Domain.NagNode", null)
                        .WithMany("NagInputs")
                        .HasForeignKey("ParentNagNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.NagLog", b =>
                {
                    b.HasOne("DailyNagger.Server.Domain.Nag", null)
                        .WithMany()
                        .HasForeignKey("NagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.NagNode", b =>
                {
                    b.HasOne("DailyNagger.Server.Domain.NagLog", null)
                        .WithMany("NagNodes")
                        .HasForeignKey("NagLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DailyNagger.Server.Domain.NagNode", null)
                        .WithMany()
                        .HasForeignKey("ParentNagNodeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.NagTime", b =>
                {
                    b.HasOne("DailyNagger.Server.Domain.Nag", null)
                        .WithMany("NagTimes")
                        .HasForeignKey("NagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.Nag", b =>
                {
                    b.Navigation("NagTimes");
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.NagLog", b =>
                {
                    b.Navigation("NagNodes");
                });

            modelBuilder.Entity("DailyNagger.Server.Domain.NagNode", b =>
                {
                    b.Navigation("NagInputs");
                });
#pragma warning restore 612, 618
        }
    }
}
