export const modalTheme = {
  button: {
    primaryBackground: "#d97828",
    singleUseBackground: "#f2d66f",
    primaryText: "#1a1b1d",
    secondaryBorder: "#d8d1c9",
    secondaryText: "#18242b",
  },
  modalButtonBody: {
    borderRadius: 1,
    minHeight: 32,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  modalButtonFooter: {
    borderRadius: 4,
    minHeight: 44,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  modalButtonTone: {
    primary: {
      background: "#d97828",
      border: "#d97828",
      text: "#18242b",
    },
    secondary: {
      background: "#f8f4ef",
      border: "#d8d1c9",
      text: "#18242b",
    },
    choice: {
      background: "#fffdf8",
      border: "#d8d1c9",
      selectedBackground: "#e7ddff",
      selectedBorder: "#b9a7df",
      text: "#18242b",
    },
  },
  modalChip: {
    borderRadius: 3,
    fontSize: 15,
    minHeight: 28,
    paddingHorizontal: 5,
    paddingVertical: 3,
    tone: {
      active: {
        background: "#f3d6bd",
        border: "#d97828",
        text: "#18242b",
      },
      preview: {
        background: "transparent",
        border: "#d97828",
        text: "#58656d",
      },
      selected: {
        background: "transparent",
        border: "#d97828",
        text: "#18242b",
      },
    },
  },
  modalChipRow: {
    gap: 6,
  },
  modalFooterActions: {
    gap: 8,
  },
  modalHeadingBelt: {
    endPadding: 96,
    gap: 18,
    itemPaddingHorizontal: 0,
    itemSize: 42,
  },
  modalHeadline: {
    activeText: "#18242b",
    fontSize: 20,
    inactiveText: "#85a9b8",
  },
  modalSegmentedControl: {
    border: "#d8d1c9",
    borderRadius: 3,
    minHeight: 28,
    selectedBackground: "#f3d6bd",
    selectedBorder: "#d97828",
    selectedText: "#18242b",
    text: "#18242b",
    unselectedBackground: "transparent",
  },
  modalSection: {
    gap: 8,
    titleActiveText: "#18242b",
    titleInactiveText: "#85a9b8",
    titleUnderline: "#354047",
    titleText: "#18242b",
  },
  modalText: {
    placeholder: "#58656d",
    status: "#58656d",
  },
  modalToggleGroup: {
    border: "#d8d1c9",
    borderRadius: 3,
    gap: 8,
    minHeight: 34,
    selectedBackground: "#f3d6bd",
    selectedBorder: "#d97828",
    selectedText: "#18242b",
    text: "#18242b",
    unselectedBackground: "transparent",
  },
  modalWheel: {
    bar: "#d97828",
    fadedText: "#8a969d",
    horizontalItemSize: 56,
    itemSize: 42,
    labelText: "#58656d",
    markedText: "#d97828",
    selectedText: "#18242b",
    text: "#58656d",
    visibleItemCount: 5,
  },
  control: {
    background: "#fffaf4",
    optionBackground: "#fffdf8",
    border: "#d8d1c9",
    text: "#18242b",
    mutedText: "#53636d",
    secondaryMutedText: "#58656d",
    placeholderText: "#6f7e87",
  },
  schedule: {
    selectedBackground: "#e7ddff",
    selectedBorder: "#b9a7df",
    primaryBackground: "#d67b32",
  },
  sheet: {
    backdrop: "#000",
    background: "#f8f4ef",
    closeIcon: "#51636d",
    contentPaddingHorizontal: 16,
    footerBorder: "#ddd6cf",
    sectionBorder: "#e4ded7",
  },
  suggestion: {
    background: "#e2dcf3",
    border: "#9fb7c3",
    exactMatchBorder: "#756b92",
  },
  rollover: {
    logBackground: "#e8ecec",
    logBorder: "#9fb7c3",
    keepBackground: "#fff2bf",
    keepBorder: "#e0bc56",
  },
  valuePicker: {
    selectedBackground: "#f3d6bd",
    selectedBorder: "#d97828",
    selectedText: "#1a1b1d",
  },
};
