import { command } from "./commandScopes";
import {
  editorCancel,
  editorDeleteOnceTaskItem,
  editorDeleteSelectedNode,
  editorMoveSelectedNodeDown,
  editorMoveSelectedNodeUp,
  editorNaggerSetScheduleRules,
  editorNaggerSetTargetTime,
  editorNaggerSetTitle,
  editorTaskEntrySetLabel,
  editorTaskEntrySetTag,
  editorTaskEntrySetValue,
  editorTaskEntrySetValueType,
  editorTaskItemSetName,
  editorTaskItemSetTag,
  editorTaskLogSetTag,
  editorSave,
  editorStartEdit,
  naggerPinSelected,
  naggerSetExpanded,
  naggerSetFocused,
  naggerUnpinSelected,
  taskEntrySetFocused,
  taskEntrySetValue,
  taskItemAddTaskEntry,
  taskItemAddTaskItem,
  taskItemDeleteOnce,
  taskItemSetDoneAndSetFocus,
  taskItemSetExpanded,
  taskItemSetFocused,
  taskLogAddTaskItem,
  taskLogAddTaskStep,
  taskLogSetFocused,
} from "./commandHandlers";

export const commandActions = {
  "editor/cancel": command("editor-session", editorCancel),
  "editor/nagger/set-schedule-rules": command("editor", editorNaggerSetScheduleRules),
  "editor/nagger/set-target-time": command("editor", editorNaggerSetTargetTime),
  "editor/nagger/set-title": command("editor", editorNaggerSetTitle),
  "editor/delete-selected-node": command("editor", editorDeleteSelectedNode),
  "editor/task-entry/set-label": command("editor", editorTaskEntrySetLabel),
  "editor/task-entry/set-tag": command("editor", editorTaskEntrySetTag),
  "editor/task-entry/set-value": command("editor", editorTaskEntrySetValue),
  "editor/task-entry/set-value-type": command("editor", editorTaskEntrySetValueType),
  "editor/task-item/delete-once": command("editor", editorDeleteOnceTaskItem),
  "editor/task-item/set-name": command("editor", editorTaskItemSetName),
  "editor/task-item/set-tag": command("editor", editorTaskItemSetTag),
  "editor/task-log/set-tag": command("editor", editorTaskLogSetTag),
  "editor/move-selected-node-down": command("editor", editorMoveSelectedNodeDown),
  "editor/move-selected-node-up": command("editor", editorMoveSelectedNodeUp),
  "editor/save": command("editor-session", editorSave),
  "editor/start-edit": command("editor-session", editorStartEdit),
  "nagger/set-expanded": command("navigation", naggerSetExpanded),
  "nagger/set-focused": command("navigation", naggerSetFocused),
  "nagger/pin-selected": command("sync", naggerPinSelected),
  "nagger/unpin-selected": command("sync", naggerUnpinSelected),
  "task-log/set-focused": command("navigation", taskLogSetFocused),
  "task-log/add-task-step": command("task-input", taskLogAddTaskStep),
  "task-log/add-task-item": command("editor", taskLogAddTaskItem),
  "task-item/set-expanded": command("navigation", taskItemSetExpanded),
  "task-item/set-focused": command("navigation", taskItemSetFocused),
  "task-item/set-done-and-set-focus": command("task-input", taskItemSetDoneAndSetFocus),
  "task-item/delete-once": command("task-input", taskItemDeleteOnce),
  "task-item/add-task-entry": command("editor", taskItemAddTaskEntry),
  "task-item/add-task-item": command("editor", taskItemAddTaskItem),
  "task-entry/set-focused": command("navigation", taskEntrySetFocused),
  "task-entry/set-value": command("task-input", taskEntrySetValue),
} as const;
