import { command } from "./commandScopes";
import {
  editorCancel,
  editorDeleteSelectedNode,
  editorMoveSelectedNodeDown,
  editorMoveSelectedNodeUp,
  editorSave,
  editorStartEdit,
  naggerPinSelected,
  naggerSetExpanded,
  naggerSetFocused,
  naggerSetScheduleRules,
  naggerSetTargetTime,
  naggerSetTitle,
  naggerUnpinSelected,
  taskEntrySetFocused,
  taskEntrySetLabel,
  taskEntrySetTag,
  taskEntrySetValue,
  taskEntrySetValueType,
  taskItemAddTaskEntry,
  taskItemAddTaskItem,
  taskItemDeleteOnce,
  taskItemSetDoneAndSetFocus,
  taskItemSetExpanded,
  taskItemSetFocused,
  taskItemSetName,
  taskItemSetTag,
  taskLogAddTaskItem,
  taskLogAddTaskStep,
  taskLogSetFocused,
  taskLogSetTag,
} from "./commandHandlers";

export const commandActions = {
  "editor/cancel": command("editor-session", editorCancel),
  "editor/delete-selected-node": command("editor-action", editorDeleteSelectedNode),
  "editor/move-selected-node-down": command("editor-action", editorMoveSelectedNodeDown),
  "editor/move-selected-node-up": command("editor-action", editorMoveSelectedNodeUp),
  "editor/save": command("editor-session", editorSave),
  "editor/start-edit": command("editor-session", editorStartEdit),
  "nagger/set-expanded": command("view", naggerSetExpanded),
  "nagger/set-focused": command("view", naggerSetFocused),
  "nagger/pin-selected": command("sync", naggerPinSelected),
  "nagger/set-schedule-rules": command("input", naggerSetScheduleRules),
  "nagger/set-target-time": command("input", naggerSetTargetTime),
  "nagger/set-title": command("input", naggerSetTitle),
  "nagger/unpin-selected": command("sync", naggerUnpinSelected),
  "task-log/set-focused": command("view", taskLogSetFocused),
  "task-log/set-tag": command("input", taskLogSetTag),
  "task-log/add-task-step": command("input", taskLogAddTaskStep),
  "task-log/add-task-item": command("editor-action", taskLogAddTaskItem),
  "task-item/set-expanded": command("view", taskItemSetExpanded),
  "task-item/set-focused": command("view", taskItemSetFocused),
  "task-item/set-done-and-set-focus": command("input", taskItemSetDoneAndSetFocus),
  "task-item/delete-once": command("input", taskItemDeleteOnce),
  "task-item/add-task-entry": command("editor-action", taskItemAddTaskEntry),
  "task-item/add-task-item": command("editor-action", taskItemAddTaskItem),
  "task-item/set-name": command("input", taskItemSetName),
  "task-item/set-tag": command("input", taskItemSetTag),
  "task-entry/set-focused": command("view", taskEntrySetFocused),
  "task-entry/set-label": command("input", taskEntrySetLabel),
  "task-entry/set-tag": command("input", taskEntrySetTag),
  "task-entry/set-value": command("input", taskEntrySetValue),
  "task-entry/set-value-type": command("input", taskEntrySetValueType),
} as const;
