// <auto-generated />
using System;
using DailyNagger.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailyNagger.Server.Data.Migrations.Control
{
    [DbContext(typeof(DailyNaggerControlDbContext))]
    partial class DailyNaggerControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DailyNagger.Server.Operations.DebugLogTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppInstanceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MinimumLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AppInstanceId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.ToTable("debug_log_targets", null, t =>
                        {
                            t.HasCheckConstraint("CK_debug_log_targets_TargetRequired", "AppInstanceId IS NOT NULL OR UserId IS NOT NULL");
                        });
                });

            modelBuilder.Entity("DailyNagger.Server.Operations.NagCommunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConnectionStringTemplate")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeactivated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_deactivated")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordSecretName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("nag_communities", (string)null);
                });

            modelBuilder.Entity("DailyNagger.Server.Operations.NagCommunityMember", b =>
                {
                    b.Property<Guid>("NagCommunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NagCommunityId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("nag_community_members", (string)null);
                });

            modelBuilder.Entity("DailyNagger.Server.Operations.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("DailyNagger.Server.Operations.NagLogCopyDelegatorStatus", b =>
                {
                    b.Property<Guid>("DelegatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("delegator_id");

                    b.Property<Guid?>("CommunityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("community_id");

                    b.Property<string>("DelegatorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("delegator_name");

                    b.Property<long>("ErrorCountSinceLastSnapshot")
                        .HasColumnType("bigint")
                        .HasColumnName("error_count_since_last_snapshot");

                    b.Property<DateTimeOffset?>("LastErrorAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_error_at");

                    b.Property<DateTimeOffset?>("LastRunFinishedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_run_finished_at");

                    b.Property<DateTimeOffset?>("LastRunStartedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_run_started_at");

                    b.Property<long>("LastRunDurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("last_run_duration_ms");

                    b.Property<int>("LastRunMaxParallelism")
                        .HasColumnType("int")
                        .HasColumnName("last_run_max_parallelism");

                    b.Property<long>("LastDbDurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("last_db_duration_ms");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_seen_at");

                    b.Property<long>("LastProcessingDurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("last_processing_duration_ms");

                    b.Property<long>("MaxDbDurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("max_db_duration_ms");

                    b.Property<long>("MaxProcessingDurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("max_processing_duration_ms");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("stopped_at");

                    b.Property<long>("TotalDbDurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("total_db_duration_ms");

                    b.Property<long>("TotalCopiedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_copied_count");

                    b.Property<long>("TotalErrorCount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_error_count");

                    b.Property<long>("TotalNoFutureOccurrenceCount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_no_future_occurrence_count");

                    b.Property<long>("TotalNoOpenLogCount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_no_open_log_count");

                    b.Property<long>("TotalProcessingDurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("total_processing_duration_ms");

                    b.Property<long>("TotalRunCount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_run_count");

                    b.Property<long>("TotalStaleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_stale_count");

                    b.HasKey("DelegatorId");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("CommunityId");

                    b.HasIndex("Status");

                    b.HasIndex("DelegatorName");

                    b.ToTable("nag_log_copy_delegator_status", (string)null);
                });

            modelBuilder.Entity("DailyNagger.Server.Operations.NagCommunityMember", b =>
                {
                    b.HasOne("DailyNagger.Server.Operations.NagCommunity", null)
                        .WithMany()
                        .HasForeignKey("NagCommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DailyNagger.Server.Operations.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
