export const nagPlanTheme = {
  screen: {
    background: "#1a1b1d",
    text: "#f4f1ed",
    accent: "#d97828",
  },
  screenDensity: {
    horizontalPadding: 8,
  },
  selection: {
    border: "#2f3b3f",
  },
  rail: {
    active: "#d97828",
    completed: "#5f7f4c",
    contentGap: 6,
    entryMarkerHeight: 22,
    entryMarkerNeutralHeight: 8,
    focusLaneWidth: 5,
    neutral: "#d6dddd",
    statusLaneWidth: 10,
  },
  nagger: {
    background: "#f4f1ed",
    selectedBackground: "#f4f1ed",
    border: "#2f3b3f",
    titleText: "#19120c",
    dueText: "#263236",
  },
  taskLog: {
    background: "#f4f1ed",
    border: "#2f3b3f",
    foldBorder: "#8d9697",
  },
  taskItem: {
    background: "#e8ecec",
    selectedBackground: "#e8ecec",
    removedOnRolloverBackground: "#fffaf3",
    border: "#2f3b3f",
    divider: "#cdd5d5",
    removedOnRolloverBorder: "#2f3b3f",
    pressedBackground: "#dfe5e5",
    titleText: "#1f3037",
    progressText: "#506269",
    chevronText: "#506269",
  },
  taskEntry: {
    labelText: "#3d4d53",
    inputBackground: "#f4f1ed",
    inputBorder: "#cfd6d8",
    inputText: "#1d2428",
    referenceText: "#8a979b",
    checkboxBackground: "#fffaf3",
    checkboxReferenceBackground: "#b8c0c3",
    checkboxCheckedBackground: "#1d2428",
    checkboxBorder: "#2f3b3f",
  },
  typography: {
    taskItemTitleSize: 17,
    taskItemTitleWeight: "700",
    taskEntryLabelSize: 15,
    taskEntryLabelWeight: "700",
    taskEntryValueSize: 15,
    taskEntryValueWeight: "700",
  },
  cardChrome: {
    borderBottomWidth: 2,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderTopWidth: 1,
  },
  cardDensity: {
    childTopPadding: 2,
    fieldGap: 2,
    fieldPaddingHorizontal: 0,
    fieldPaddingVertical: 0,
    naggerRailGap: 6,
    naggerPadding: 4,
    taskItemPadding: 2,
    taskLogPadding: 4,
  },
  radius: {
    card: 1,
    focusFrame: 1,
    control: 1,
    checkbox: 2,
  },
  spacing: {
    screen: 24,
    nagger: 16,
    taskLog: 10,
    taskItem: 10,
    taskItemChildrenTop: 8,
    listGap: 12,
    listBottomComfortScreenRatio: 0.5,
  },
} as const;
