export const nagPlanTheme = {
  screen: {
    background: "#1a1b1d",
    text: "#f4f1ed",
    accent: "#d97828",
  },
  screenDensity: {
    horizontalPadding: 8,
  },
  selection: {
    border: "#5f3519",
    shadow: "#2b180c",
  },
  nagger: {
    background: "#c86f2a",
    selectedBackground: "#e17c27",
    border: "#b9682c",
    titleText: "#19120c",
    dueText: "#3b2614",
  },
  taskLog: {
    background: "#f4f1ed",
    border: "#e2ded8",
  },
  taskItem: {
    background: "#e8ecec",
    selectedBackground: "#dfe8e8",
    removedOnRolloverBackground: "#fffaf3",
    border: "#d8dddd",
    removedOnRolloverBorder: "#d8d1c9",
    pressedBackground: "#dfe5e5",
    titleText: "#1f3037",
    progressText: "#506269",
    chevronText: "#506269",
  },
  taskEntry: {
    labelText: "#3d4d53",
    inputBackground: "#f4f1ed",
    inputBorder: "#cfd6d8",
    inputText: "#1d2428",
    referenceText: "#8a979b",
    checkboxBackground: "#fffaf3",
    checkboxReferenceBackground: "#b8c0c3",
    checkboxCheckedBackground: "#1d2428",
    checkboxBorder: "#1d2428",
  },
  cardChrome: {
    borderBottomWidth: 3,
    borderLeftWidth: 2,
    borderRightWidth: 3,
    borderTopWidth: 2,
  },
  cardDensity: {
    fieldGap: 4,
    fieldPaddingHorizontal: 2,
    fieldPaddingVertical: 2,
    padding: 8,
  },
  radius: {
    card: 8,
    focusFrame: 10,
    control: 6,
    checkbox: 7,
  },
  spacing: {
    screen: 24,
    nagger: 16,
    taskLog: 10,
    taskItem: 10,
    taskItemChildrenTop: 8,
    listGap: 12,
    listBottomComfortScreenRatio: 0.5,
  },
} as const;
