export const postOfficeStripConfig = {
  stripWidth: 360,
  queueSlotCount: 16,
  exitSlotCount: 6,
  tickMs: 180,
  defaultParcelEmoji: "👽",
  unknownMoodEmoji: "👽",
  postBoxEmoji: "📮",
  blockedPostBoxEmoji: "📪",
  coalescedEmoji: "👻",
  sentEmoji: "👍",
  rejectedEmoji: "😱",
  failedToConnectEmoji: "😴",
  blockedEmoji: "🤬",
  discardedEmoji: "🗑️",
  forcedEmoji: "🥸",
  waitingStages: [
    { afterMs: 5_000, emoji: "🫩" },
    { afterMs: 12_000, emoji: "🥱" },
    { afterMs: 25_000, emoji: "😴" },
  ],
  resultFrameCount: 6,
  maxVisibleParcels: 10,
} as const;
