import { command } from "../commandScopes";
import {
  editorDeleteOnceTaskItem,
  editorDeleteSelectedNode,
  editorMoveSelectedNodeDown,
  editorMoveSelectedNodeUp,
  editorNaggerPinSelected,
  editorNaggerSetScheduleRules,
  editorNaggerSetTargetTime,
  editorNaggerSetTitle,
  editorNaggerUnpinSelected,
  editorTaskEntrySetLabel,
  editorTaskEntrySetTag,
  editorTaskEntrySetValue,
  editorTaskEntrySetValueType,
  editorTaskItemSetName,
  editorTaskItemSetTag,
  editorTaskLogSetTag,
  taskItemAddTaskEntry,
  taskItemAddTaskItem,
  taskLogAddTaskItem,
} from "../commandHandlers";

export const editorCommandActions = {
  "editor/nagger/set-schedule-rules": command("editor", editorNaggerSetScheduleRules),
  "editor/nagger/pin-selected": command("editor", editorNaggerPinSelected),
  "editor/nagger/unpin-selected": command("editor", editorNaggerUnpinSelected),
  "editor/nagger/set-target-time": command("editor", editorNaggerSetTargetTime),
  "editor/nagger/set-title": command("editor", editorNaggerSetTitle),
  "editor/delete-selected-node": command("editor", editorDeleteSelectedNode),
  "editor/task-entry/set-label": command("editor", editorTaskEntrySetLabel),
  "editor/task-entry/set-tag": command("editor", editorTaskEntrySetTag),
  "editor/task-entry/set-value": command("editor", editorTaskEntrySetValue),
  "editor/task-entry/set-value-type": command("editor", editorTaskEntrySetValueType),
  "editor/task-item/delete-once": command("editor", editorDeleteOnceTaskItem),
  "editor/task-item/set-name": command("editor", editorTaskItemSetName),
  "editor/task-item/set-tag": command("editor", editorTaskItemSetTag),
  "editor/task-log/set-tag": command("editor", editorTaskLogSetTag),
  "editor/move-selected-node-down": command("editor", editorMoveSelectedNodeDown),
  "editor/move-selected-node-up": command("editor", editorMoveSelectedNodeUp),
  "task-log/add-task-item": command("editor", taskLogAddTaskItem),
  "task-item/add-task-entry": command("editor", taskItemAddTaskEntry),
  "task-item/add-task-item": command("editor", taskItemAddTaskItem),
} as const;
