/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/database": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    communityId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NaggerDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JsonElement"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NaggerDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todays-nag-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    communityId: string;
                    userId: string;
                    date: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NagPlanDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nag-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    communityId: string;
                    userId: string;
                    date: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NagPlanDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task-logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JsonElement"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskLogDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task-logs/{id}/task-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTaskEntryValuesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskLogVersionDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    communityId: string;
                    userId: string;
                    tagType: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TagDto"][];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveTagRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TagDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/naggers/{naggerId}/task-step-name-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    communityId: string;
                    userId: string;
                };
                header?: never;
                path: {
                    naggerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskStepNameSuggestionDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-moods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    communityId: string;
                    userId: string;
                    from?: string;
                    to?: string;
                    take?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveUserMoodRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ClientIdentityDto: {
            clientId: string;
            deviceName: string;
            deviceModel: string;
        };
        JsonElement: unknown;
        NaggerDto: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: date */
            activeLogDueOn: null | string;
            /** Format: date */
            expiresOn: null | string;
            /** Format: time */
            targetTime: null | string;
            isDeactivated: boolean;
            pinnedBy: components["schemas"]["NaggerPinnedByDto"];
            /** Format: date-time */
            updatedAt: string;
            updatedByClientId: null | string;
            updatedByDeviceName: null | string;
            updatedByDeviceModel: null | string;
            scheduleRules: components["schemas"]["ScheduleRuleDto"][];
            /** Format: int32 */
            version: number | string;
        };
        /** @enum {unknown} */
        NaggerPinnedByDto: "None" | "User" | "Llm" | "Community";
        NagPlanDto: {
            /** Format: date */
            date: string;
            nags: components["schemas"]["NagPlanNaggerDto"][];
        };
        NagPlanNaggerDto: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: date */
            activeLogDueOn: null | string;
            /** Format: date */
            expiresOn: null | string;
            /** Format: time */
            targetTime: null | string;
            isDeactivated: boolean;
            pinnedBy: components["schemas"]["NaggerPinnedByDto"];
            /** Format: date-time */
            updatedAt: string;
            updatedByClientId: null | string;
            updatedByDeviceName: null | string;
            updatedByDeviceModel: null | string;
            scheduleRules: components["schemas"]["ScheduleRuleDto"][];
            taskLog: components["schemas"]["TaskLogDto"];
            /** Format: int32 */
            version: number | string;
        };
        /**
         * @default Keep
         * @enum {unknown}
         */
        RolloverBehaviorDto: "Keep" | "Remove" | "RemoveWhenDone" | "MoveValueToHistory" | "CarryOverValue";
        SaveTagRequest: {
            /** Format: uuid */
            communityId: string;
            /** Format: uuid */
            userId: string;
            tagType: string;
            name: string;
            description: null | string;
        };
        SaveUserMoodPayload: {
            /** Format: uuid */
            id: string;
            mood: string;
            /** Format: date-time */
            recordedAt: string;
            timeZone?: null | string;
            locale?: null | string;
        };
        SaveUserMoodRequest: {
            /** Format: uuid */
            communityId: string;
            /** Format: uuid */
            userId: string;
            payload: components["schemas"]["SaveUserMoodPayload"];
            clientIdentity?: null | components["schemas"]["ClientIdentityDto"];
        };
        ScheduleRuleDto: {
            /** Format: uuid */
            id: string;
            ruleType: components["schemas"]["ScheduleRuleTypeDto"];
            ruleJson: string;
        };
        /** @enum {unknown} */
        ScheduleRuleTypeDto: "Weekday" | "Date" | "Holiday";
        TagDto: {
            name: string;
            description: null | string;
            /** Format: date-time */
            lastUsedAt: null | string;
        };
        TaskEntryDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            taskLogId: string;
            /** Format: uuid */
            parentTaskItemId: string;
            label: string;
            description: null | string;
            valueType: components["schemas"]["TaskEntryValueTypeDto"];
            tag: null | string;
            value: null | string;
            lastTaskRunReferenceValue?: null | string;
            rolloverBehavior?: components["schemas"]["RolloverBehaviorDto"];
            /** Format: date-time */
            interactionAt?: null | string;
            interactionTimeZone?: null | string;
            interactionLocale?: null | string;
            interactionMood?: null | string;
            /** Format: date-time */
            interactionMoodAt?: null | string;
        };
        /** @enum {unknown} */
        TaskEntryValueTypeDto: "Text" | "Integer" | "Decimal" | "Boolean";
        TaskEntryValueUpdateDto: {
            /** Format: uuid */
            id: string;
            value: null | string;
            /** Format: date-time */
            interactionAt?: null | string;
            interactionTimeZone?: null | string;
            interactionLocale?: null | string;
            interactionMood?: null | string;
            /** Format: date-time */
            interactionMoodAt?: null | string;
        };
        TaskItemDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            taskLogId: string;
            /** Format: uuid */
            parentTaskItemId: null | string;
            name: string;
            taskEntries: components["schemas"]["TaskEntryDto"][];
            taskItems: components["schemas"]["TaskItemDto"][];
            tag?: null | string;
            /** @default false */
            isDone: boolean;
            rolloverBehavior?: components["schemas"]["RolloverBehaviorDto"];
            /** Format: date-time */
            interactionAt?: null | string;
            interactionTimeZone?: null | string;
            interactionLocale?: null | string;
            interactionMood?: null | string;
            /** Format: date-time */
            interactionMoodAt?: null | string;
            /**
             * Format: int32
             * @default 0
             */
            descendantTaskItemCount: number | string;
            /**
             * Format: int32
             * @default 0
             */
            doneDescendantTaskItemCount: number | string;
        };
        TaskLogDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            nagId: string;
            /** Format: uuid */
            copiedFromTaskLogId: null | string;
            /** Format: date-time */
            closedOn: null | string;
            /** Format: date-time */
            updatedAt: string;
            updatedByClientId: null | string;
            updatedByDeviceName: null | string;
            updatedByDeviceModel: null | string;
            /** Format: int32 */
            version: number | string;
            taskItems: components["schemas"]["TaskItemDto"][];
            tag?: null | string;
            /**
             * Format: int32
             * @default 0
             */
            descendantTaskItemCount: number | string;
            /**
             * Format: int32
             * @default 0
             */
            doneDescendantTaskItemCount: number | string;
        };
        TaskLogVersionDto: {
            /** Format: int32 */
            version: number | string;
            /** Format: date-time */
            updatedAt: string;
        };
        TaskStepNameSuggestionDto: {
            name: string;
        };
        UpdateTaskEntryValuesRequest: {
            /** Format: uuid */
            communityId: string;
            /** Format: uuid */
            userId: string;
            payload: components["schemas"]["TaskEntryValueUpdateDto"][];
            /** Format: date-time */
            updatedAt: string;
            /** Format: int32 */
            baseVersion: number | string;
            /** Format: int32 */
            nextVersion: number | string;
            clientIdentity?: null | components["schemas"]["ClientIdentityDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
